### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Lockless404** [ntazelo/Portfolio#14]
Excellent work Eloi, the webpage looks amazing, you might need a few touch-ups to increase the quality of your page. I suggest you move the background-position of one of the objects in your mobile version to increase visibility.

**Comment by GintsM** [comment]
Nice work. Thanks for sharing your code. My suggestions - contact form in rounded corner you can see a body background, that should be white. so  one way to solve could be make one more wrapper for all section <section class="contact-cont-form"> with a background #fff 
Also for main section you should expand for all screen, suggestions- to improve it take a all section inside some wrapper with a padding.
